<a href="https://colab.research.google.com/github/Kavishka2401/CustomerChurnPredictionSystem/blob/master/nn_featureEng_classWeights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount the google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Provide path
data=pd.read_csv('/content/drive/MyDrive/processed_data_NN.csv')

In [4]:
data_model_2 = data.copy()

In [5]:
# 1. Average monthly charge per tenure
# Adding 1 to tenure to avoid division by zero
data_model_2['AvgChargePerMonth'] = data_model_2['TotalCharges_numeric'] / (data_model_2['tenure'] + 1)

# 2. Service usage count
# List of columns representing optional services (already one-hot encoded as 0/1)
service_cols = [
    'OnlineSecurity_Yes', 'OnlineBackup_Yes', 'DeviceProtection_Yes',
    'TechSupport_Yes', 'StreamingTV_Yes', 'StreamingMovies_Yes'
]

# Sum the services used by each customer
data_model_2['ServiceCount'] = data_model_2[service_cols].sum(axis=1)

# Check first few rows to confirm
data_model_2[['AvgChargePerMonth', 'ServiceCount']].head()

   AvgChargePerMonth  ServiceCount
0          29.441096             1
1        1283.433962             2
2         105.227027             2
3        1132.769231             3
4         147.551351             0

In [7]:
from sklearn.preprocessing import MinMaxScaler

# Initialize scaler
scaler = MinMaxScaler()

# List of numeric features to scale
num_features_to_scale = ['AvgChargePerMonth', 'ServiceCount']

# Fit scaler on these columns and transform
data_model_2[num_features_to_scale] = scaler.fit_transform(data_model_2[num_features_to_scale])

# Check the result
data_model_2[num_features_to_scale].describe()
data_model_2.head()

,customerID,tenure,MonthlyCharges,TotalCharges,Churn,TotalCharges_numeric,TotalCharges_log,gender_Male,SeniorCitizen_1,Partner_Yes,...,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,AvgChargePerMonth,ServiceCount
0,7590-VHVEG,0.013889,0.115423,29.85,0,29.85,0.072892,0,0,1,...,0,0,0,0,1,0,1,0,0.002521,0.166667
1,5575-GNVDE,0.472222,0.385075,1889.5,0,1889.50,0.749358,1,0,0,...,0,0,1,0,0,0,0,1,0.292538,0.333333
2,3668-QPYBK,0.027778,0.354229,108.15,1,108.15,0.280590,1,0,0,...,0,0,0,0,1,0,0,1,0.020048,0.333333
3,7795-CFOCW,0.625000,0.239303,1840.75,0,1840.75,0.745063,1,0,0,...,0,0,1,0,0,0,0,0,0.257693,0.500000
4,9237-HQITU,0.027778,0.521891,151.65,1,151.65,0.335724,0,0,0,...,0,0,0,0,1,0,1,0,0.029837,0.000000